app = 'live-svg-ball'
primary_region = 'ams'
kill_signal = 'SIGTERM'

[build]

[env]
  PHX_HOST = 'live-svg-ball.fly.dev'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  size = 'shared-cpu-1x'
